### ISSUE TITLE
Has no method 'reload'

### ISSUE THREAD

**Issue by michaelgrossklos** [micahblu/gulp-connect-php#3]
I use the plugin as mentioned in your Readme with the `.pipe(connect.reload());`command. But I get an error: `TypeError: Object #<Object> has no method 'reload'`. Also `open:true` isn't working at all. Here's my code:

``` javascript
var gulp = require('gulp'),
    jade = require('gulp-jade'),
    sass = require('gulp-sass'),
    browserify = require('gulp-browserify'),
    prefixer = require('gulp-autoprefixer'),
    connect = require('gulp-connect-php'),
    uglify = require('gulp-uglify'),
    rename = require('gulp-rename');

gulp.task('connect', connect.server({
    base: ['../../../'],
    open: true
}));

gulp.task('jade', function(){
    return gulp.src('src/templates/**/*.jade')
        .pipe(jade())
        .pipe(gulp.dest('./js'))
        .pipe(connect.reload());
});

gulp.task('css', function(){
    return gulp.src('css/**/*.scss')
        .pipe(sass({style: 'compressed'}))
        .pipe(prefixer({
            browsers: ['last 15 version', 'ie', 'iOS', 'Safari', 'ChromeAndroid', 'ExplorerMobile', 'Chrome', 'Android'],
            cascade:false
        }))
        .pipe(rename('css/**/style.css'))
        .pipe(gulp.dest('./'))
        .pipe(connect.reload());
});

gulp.task('php', function(){
    gulp.src('./**/*.php')
        .pipe(connect.reload());
});

gulp.task('watch', function(){
    gulp.watch('src/templates/**/*.jade', ['jade']);
    gulp.watch('css/**/*.scss', ['css']);
    gulp.watch('./**/*.php', ['php']);
});

gulp.task('default', ['watch', 'connect']);
```

**Comment by micahblu** [comment]
Sorry for delay, looking into this tonight, hope to have a patch soon

**Comment by KanatSakhanov** [comment]
I have the same problem. Do you have not yet found a solution to this problem?

**Comment by micahblu** [comment]
Actually this is not a bug, its not a supported feature. Gulp connect offers livereload feature which is utilized by the reload method. I would like to add this feature, however my plate's pretty full these days so it may take some time before I can get to it. I am completely happy to merge if anyone is up for it :)

**Comment by iskrisis** [comment]
Hi, i have the same thing. Would love too help out fixing it but i have no skills to do that (fcking designers).

Anyway you taged it enhancement so that means that there is some way too go around this? Older version of connect or something? 

By the way thanks, you have no idea how these little tools and wrappers help out others.

**Comment by nagaxiii** [comment]
Hi there,

I've bumped into the same problem and I can show you the workaround I found if you don't insist on the LiveReload.

You can achieve the desired effect with [BrowserSync](http://www.browsersync.io/docs/gulp/)  as well. In this plugin, you can use an existing webserver (like this gulp-connect-php) and pass it as a proxy.

Let me show a very minimal setup which solves the reloading problem (`gulpfile.js`):

``` javascript
var gulp        = require('gulp')
  , php         = require('gulp-connect-php')
  , browserSync = require('browser-sync');

gulp.task('default', function() {
    php.server({
        hostname: 'localhost'
    });

    browserSync({
        proxy: "localhost:8000"
    });

    gulp.watch('**/*.php').on('change', browserSync.reload());
});
```

Please note that for BrowserSync you need to have a `<body></body>` tag on your page, because it needs some code injected there in order to work.

Hope it helps you.
Cheers!

**Comment by micahblu** [comment]
Thanks to inagaxiii and saacalves for pointing out the ease of integrating BrowserSync with gulp-connect-php. Below is a snippet of a working example using BrowserySync to live reload the browser while editing php files. Enjoy

``` javascript
var gulp = require('gulp'),
    connect = require('gulp-connect-php'),
    browserSync = require('browser-sync');

gulp.task('connect-sync', function() {
  connect.server({}, function (){
    browserSync({
      proxy: 'localhost:8000'
    });
  });

  gulp.watch('**/*.php').on('change', function () {
    browserSync.reload();
  });
});
```

**Comment by iskrisis** [comment]
Thanks! DABEST
