### ISSUE TITLE
Is there a way to automatically add URL extensions?

### ISSUE THREAD

**Issue by ekfuhrmann** [micahblu/gulp-connect-php#50]
I am trying to run `gulp-connect-php` along with `browser-sync` so that I can locally run some `.php` files. 

Here is the task I'm currently running:

```
gulp.task('connect', () => {
  return connect.server({ 
    base: config.wpFolder,
    open: true,
    port: 8080
  }, function(){
    browserSync.init({
      proxy: '127.0.0.1:8080',
      files       : [`${config.wpFolder}/*.php`],
      notify      : false,
      ui: {
        port: 8080
      }
    });
  });
});
```

Now this does work for index as expected; however my issue is when I try and go to a different page. If I'm on `localhost:8000` and then click the link to the contact page, the URL will update to `localhost:8000/contact`; however, it still only loads the index page. If I manually append `.php` so that the url reads `localhost:8000/contact.php`, it works.

Is there any way I can automate appending `.php` so that I don't need to update all of the URL's? For a production release, I would not have `.php` in the URL so I'd have to remove it for that and would like to keep the build process as DRY as possible.

**Comment by grmartin** [comment]
Let me start by saying... 

1. I know relatively little about `browser-sync`
2. Directly. No.

However, you can cheat. Judging purely by the name of that variable you passed in i assume the `wp` to stand for WordPress... WordPress as well as many PHP websites use Apache's (or equivalent in other environments) `mod_rewrite`, PHP's dev server is SUPER simple and doesn't implement such a functionality... However it does permit you to roll your own basic compatibility layer...

You want to supply a `router` command to `connect.server`. This should be a relative path to a `.php` file. Basically, PHP will invoke this file on EVERY CALL. You choose what to return as data (and set your own headers) or to `include` in to that invocation of PHP for the request. This will allow you to examine `$_SERVER['REQUEST_URI']` for a file without a `.php` ending and `include`/`require` it if it exists... This will be invoked for EVERY call, that means resources too... so if it ends in an extension you will be responsible for outputting the `Content-Type` header (`http://php.net/manual/en/book.fileinfo.php` might help here... though i relied on Node's `mime-db` module which i parsed via the JSON decoder because fileinfo wasnt available in all cases for the project i was on) as well as outputting the data (as simple as `print file_get_contents($actualFilePath)`...

**Comment by ekfuhrmann** [comment]
Sorry about not clarifying that it was indeed relating to a Wordpress build. Thanks for the detailed writeup on how I could work around my issue. Unfortunately due to some other circumstances I can't go about syncing the files as I originally wanted for a localhost anyway, though what you provided was helpful for possible future work.

Thanks for the assistance.
